name: Deploy to Virtual Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH keys from GitHub Secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to the VM via SSH
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}           # Virtual machine host (IP address 
or domain)
          username: ${{ secrets.VM_USER }}       # SSH username (e.g., 'ubuntu')
          key: ${{ secrets.SSH_PRIVATE_KEY }}    # SSH private key stored in GitHub 
Secrets
          port: 22                              # Default SSH port, can be adjusted
          script: |
            cd /path/to/your/project            # Change to the project directory
            git pull origin main                # Pull the latest code from the main 
branch
            sudo systemctl restart your-service # Restart your service to apply the 
changes

      # Send notification on success
      - name: Send Notification
        run: echo "Deployment Successful"




