name: Deploy to Virtual Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}           
          username: ${{ secrets.VM_USER }}       
          key: ${{ secrets.SSH_PRIVATE_KEY }}    
          port: 22                              
          script: |
            cd /path/to/your/project            
            git pull origin main                
            sudo systemctl restart your-service 

      - name: Send Notification
        run: echo "Deployment Successful"
